---
botify:
  username: cameron.gagnon+spotify@gmail.com
  password: g5Prw9fsDHupW7u
  playlist: spotify:user:cmag1995:playlist:1R4zAAeGmZ8zXFcBZnYY34
  scope: "playlist-modify-private user-read-playback-state user-modify-playback-state"
  client_id: 6702f26eea054f2193a273a58109ff51
  client_secret: 7b6a8cc19d264998922a7c67575d2cb3
  redirect_uri: https://localhost:8080

listener:
  oauth_token: a9q971u4b3m0ffb0elw5mdyqt99ujj
