"""empty message

Revision ID: 2f958344d175
Revises: c5123a115125
Create Date: 2019-06-15 18:43:18.611406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f958344d175'
down_revision = 'c5123a115125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_song_request_requester', table_name='song_request')
    op.create_index(op.f('ix_song_request_requester'), 'song_request', ['requester'], unique=False)
    op.drop_index('ix_song_request_song_type', table_name='song_request')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_song_request_song_type', 'song_request', ['song_type'], unique=1)
    op.drop_index(op.f('ix_song_request_requester'), table_name='song_request')
    op.create_index('ix_song_request_requester', 'song_request', ['requester'], unique=1)
    # ### end Alembic commands ###
