"""empty message

Revision ID: 4e021c6ee5bb
Revises: 2f958344d175
Create Date: 2019-06-15 18:44:10.116801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e021c6ee5bb'
down_revision = '2f958344d175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_song_request_artist', table_name='song_request')
    op.create_index(op.f('ix_song_request_artist'), 'song_request', ['artist'], unique=False)
    op.drop_index('ix_song_request_name', table_name='song_request')
    op.create_index(op.f('ix_song_request_name'), 'song_request', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_song_request_name'), table_name='song_request')
    op.create_index('ix_song_request_name', 'song_request', ['name'], unique=1)
    op.drop_index(op.f('ix_song_request_artist'), table_name='song_request')
    op.create_index('ix_song_request_artist', 'song_request', ['artist'], unique=1)
    # ### end Alembic commands ###
