"""empty message

Revision ID: c5123a115125
Revises: 
Create Date: 2019-06-15 18:30:28.038419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5123a115125'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester', sa.String(length=128), nullable=True),
    sa.Column('song_type', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('artist', sa.String(length=128), nullable=True),
    sa.Column('link', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_song_request_artist'), 'song_request', ['artist'], unique=True)
    op.create_index(op.f('ix_song_request_link'), 'song_request', ['link'], unique=True)
    op.create_index(op.f('ix_song_request_name'), 'song_request', ['name'], unique=True)
    op.create_index(op.f('ix_song_request_requester'), 'song_request', ['requester'], unique=True)
    op.create_index(op.f('ix_song_request_song_type'), 'song_request', ['song_type'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_song_request_song_type'), table_name='song_request')
    op.drop_index(op.f('ix_song_request_requester'), table_name='song_request')
    op.drop_index(op.f('ix_song_request_name'), table_name='song_request')
    op.drop_index(op.f('ix_song_request_link'), table_name='song_request')
    op.drop_index(op.f('ix_song_request_artist'), table_name='song_request')
    op.drop_table('song_request')
    # ### end Alembic commands ###
